### ISSUE TITLE
Snapshot publish failed on scala 3 branch

### ISSUE THREAD

**Issue by armanbilge** [erikerlandson/coulomb#235]
Nothing critical, just to track this.

https://github.com/erikerlandson/coulomb/runs/5102368157

To setup snapshot publishing all that's needed is setting the `SONATYPE_USERNAME` and `SONATYPE_PASSWORD` secrets for the repo. No PGP key is needed for publishing snapshots, so you can set that up later.

**Comment by erikerlandson** [comment]
@armanbilge  I have the publish working now :tada: 

I had some trouble getting `PGP_SECRET` configured properly:  I kept getting `base64: invalid input`. The problem was that my `base64` was breaking the output into multiple lines, and over on github it expected a single base64 string with no `\n` in it.

Recommend one of two possible solutions, either:
1. update `sbt-typelevel` quickstart to say `gpg --armor --export-secret-keys $LONG_ID | base64 -w0`  (i.e. tell base64 to not split the output into lines)
or
2. change the github action to use `base64 -di`, to ignore the newlines

**Comment by armanbilge** [comment]
Very nice! 🎉 

Ah, I think I've run into that problem before msyelf, I think mac/linux behave differently there for some reason 🤔 Thanks for those pointers (much appreciated!), actually I see no reason not to apply both solutions to cover all bases :) I'll make it an issue in sbt-typelevel.
