### ISSUE TITLE
Use more specialized type classes instead of Numeric

### ISSUE THREAD

**Issue by mhriemers** [erikerlandson/coulomb#57]
Currently, all classes in the `unitops` package have a hard dependency on `Numeric[N]` whilst this could be more specialized. 

An example of what such a specialized operation would look like:
```scala
trait UnitMultiply[N1, U1, N2, U2] {
  def times(x: N1, y: N2): N1
  type RT12
}
object UnitMultiply {
  type Aux[N1, U1, N2, U2, R12] = UnitMultiply[N1, U1, N2, U2] {
    type RT12 = R12
  }
  implicit def evidence[N1, U1, N2 : ConvertableFrom, U2](implicit
                                        ms: MultiplicativeSemigroup[N1],
                                        ct: ConvertableTo[N1],
                                        mrt12: MulResultType[U1, U2]): Aux[N1, U1, N2, U2, mrt12.Out] =
    new UnitMultiply[N1, U1, N2, U2] {
      def times(x: N1, y: N2): N1 = ms.times(x, ct.fromType[N2](y))
      type RT12 = mrt12.Out
    }
}
```

**Comment by erikerlandson** [comment]
Hi @ipsq!  IIRC, Libra did something like that. That would also be a way to support #13. I've actually been leaning toward removing any requirements on `N` in the class itself, and possibly factoring out the numeric operations into an implicit class, making the core `Quantity` a bit leaner.

**Comment by mhriemers** [comment]
I'd be all for it. We are using some optimized numeric types in conjunction with `refined` skipping heavy calculations when the type system offers certain guarantees.

**Comment by erikerlandson** [comment]
this generalization raises a couple questions I don't have obvious answers for. Taking the basic numeric operators `+, -, *, /` as an example, the proper `typelevel/algebra` type classes would be:
* `+`: AdditiveSemigroup
* `-`: AdditiveGroup
* `*`: MultiplicativeSemigroup
* `/`: MultiplicativeGroup

Currently, the implicit data structure that represents unit definitions encodes the conversion coefficients for derived units via a `Rational`.  That integrates well enough with pretty much any data type adhering to the `spire/Numeric` type class, since these are all scalar numerics themselves.

However, the more general type classes above will admit types that aren't themselves scalar. Complex numbers and matrices, for example.  These two examples at least have a well-defined notion of what it means to be multiplied by a scalar but I'm not sure all examples of MultiplicativeSemigroup, etc, support a definition scalar multiplication.

It also raises the question of whether 'scalar conversion coefficient' is even the right type. If my multiplicative semigroup is `Complex`, does that imply I should be using unit definitions where the conversion coefficient is also complex?  Likewise for matrices?

Are your custom types representations of scalar numeric types?

Another example: I currently make use of the `spire/Numeric` type for guaranteeing that I can convert between types. This is to allow things like mixing numeric types in unit expressions, paralleling the way one can do `3 + 3.14`.  However, more general type classes like `AdditiveGroup` do not support this guarantee, so I'd also either have to restrict this feature, or provide another typeclass that will allow such conversions. Restricting them might not be a bad policy, but it's a change from the current behavior.

**Comment by erikerlandson** [comment]
@ipsq my original concept, IIRC, was that if someone wanted to use a new kind of numeric type, the approach would be to define a corresponding `spire/Numeric` typeclass instance for it. Is that something that would work for your custom types?

**Comment by erikerlandson** [comment]
I'm not even sure "scalar numeric" is quite sufficient - the field `integers mod n, for prime n` is a field but it's not obvious to me whether it's well defined to declare a unit system over that.

**Comment by erikerlandson** [comment]
I think I have worked out how to make progress with this. I'm making some calls to things like `uc.n1.plus(value, uc.cv21(rhs.value))` and I've already abstracted the conversion with `cv21` in a way that allows for specialization.  I just need do the same thing with `n1.plus` - turn that into `uc.plus`, and then I can specialize rules in the right way.

I'll try to work on this soon

**Comment by erikerlandson** [comment]
@ipsq I have pushed a pr for this, as a core refactoring for 0.4.x
https://github.com/erikerlandson/coulomb/pull/66

coulomb core logic is now fully algebra-ized, and completely decoupled from Numeric.

**Comment by erikerlandson** [comment]
Closing this with #66, feel free to re-open if it isn't meeting people's needs
